config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { registrations: "registrations"}
  resources :posts
  root to: 'home#index'
  get 'about', to: 'home#about'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
    attr_accessor :country_code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_admin!, :except => [:show, :index]

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    r = ISO3166::Country.find_country_by_alpha2(@post.country)
    
    @post.region = r.region
    @post.subregion = r.subregion
    
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
    
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :description, :image_url))
        redirect_to @post
    else
        render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to root_path
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :image_url, :country)
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_admin_registered?, only: [:new, :create]
  
  protected

  def one_admin_registered?
    if ((Admin.count == 1) & (admin_signed_in?))
      redirect_to root_path
    elsif Admin.count == 1
      redirect_to new_admin_session_path
    end  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<div class="container text-center">
    <br><br>
    <h1>About</h1>
    <p>Travelling is something I enjoy doing very much but, like most people, it's a slow-moving hobby. So I created this blog as a way to "wish list" some travel destinations and when it comes time to actually go there, they'll be nice and categorized so I can hit a few in one trip.</p>
</div>

app/views/home/index.html.erb
<header class="intro-header" style="background-image: url('https://images.unsplash.com/photo-1494822493217-c9840aba840c?dpr=1.25&auto=format&fit=crop&w=1500&h=2250&q=80&cs=tinysrgb&crop=&bg=')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>My Travel Wishlist</h1>
                    <hr class="small">
                    <span class="subheading">Kevin Windisch</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <% posts = Post.paginate(:page => params[:page], :per_page => 5) %>

            <% posts.order(created_at: :desc).each do |post| %>
            <div class="post-preview">
                <%= link_to post do %>
                    <h2 class="post-title">
                        <%= post.title %>
                    </h2>
                    <h3 class="post-subtitle">
                        <%= ISO3166::Country.find_country_by_alpha2(post.country).name %>
                    </h3>
                <% end %>
                <p class="post-meta">Posted on <%= post.created_at.strftime("%B %d, %Y") %></p>
            </div>
            <hr>
            <% end %>
            
            <!-- Pager -->
            <ul class="pager">
                <%= will_paginate posts %>
            </ul>
        </div>
    </div>
</div>

    <hr>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Travel Blog">
    <meta name="author" content="Kevin Windisch">

    <title>My Travel Wishlist</title>
    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
      <!-- jQuery -->
    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
    
    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/">My Travel Wishlist</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Regions<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="/posts?=Africa">Africa</a></li>
                        <li><a href="/posts?=Americas">Americas</a></li>
                        <li><a href="/posts?=Asia">Asia</a></li>
                        <li><a href="/posts?=Europe">Europe</a></li>
                        <li><a href="/posts?=Oceania">Oceania</a></li>
                      </ul>
                    </li>
                    <li>
                        <a href="/about">About</a>
                    </li>
                    <% if admin_signed_in? %>
                        <li><%= link_to 'New Post', new_post_path %></li>
                        <li><%= link_to('logout', destroy_admin_session_path, method: :delete) %></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <br><br>
<%= yield %>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="http://www.github.com/cabbagebeard" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                            <span class="fa-stack fa-lg">
                                <br>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="http://www.linkedin.com/in/kevin-windisch" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-linkedin-square fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Kevin Windisch 2017</p>
                <% if not admin_signed_in? %>
                   <p class="copyright text-muted"><%= link_to 'Admin Login', new_admin_session_path %></p>
                <% end %>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
    <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %>  prevented this post from saving </h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %> <br>
    </p>
    
    <p>
        <%= f.label :country %><br>
        <%= f.country_select :country %>
        <!-- SAVES AS alpha2 CODE -->
    </p>
    
    <p>
        <%= f.label :image_url %><br>
        <%= f.text_area :image_url %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
    <div class="text-center">
        <br><br><br>
        <h1>Edit Post</h1>
        <%= render 'form' %>
    </div>
</div>

app/views/posts/index.html.erb
<% continent = request.original_fullpath.split('=').last %>
<!-- GRABS CONTINENT FROM URL PATH -->

<% if continent == "Africa" %> 
    <% continent_img = "http://famouswonders.com/wp-content/uploads/2009/03/serengeti-landscape.jpg" %>
    <% elsif continent == "Americas" %>
        <% continent_img = "http://bossfight.co/wp-content/uploads/2016/03/boss-fight-free-high-quality-stock-images-photos-photography-river-forest-trees.jpg" %>
    <% elsif continent == "Asia" %>
        <% continent_img = "https://www.i-to-i.com/wp-content/uploads/2016/03/china-header2.jpg" %>
    <% elsif continent == "Europe" %>
        <% continent_img = "https://image.jimcdn.com/app/cms/image/transf/dimension=1190x10000:format=jpg/path/sa6549607c78f5c11/image/i3aeb4db7d64c8c69/version/1453912088/neuschwanstein-castle-bavaria-germany-best-castles-in-europe.jpg" %>
    <% elsif continent == "Oceania" %>
        <% continent_img = "http://culturewhiz.org/sites/default/files/images/destinations/Oceania.original.1725.jpg" %>
    <% else %>
        <% continent = nil %>
<% end %>

<% if continent %>
<header class="intro-header" style="background-image: url(<%= continent_img %>)">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1><%= continent %></h1>
                    <hr class="small">
                </div>
            </div>
        </div>
    </div>
</header>

<% posts = Post.where(region: continent).order(subregion: :asc) %>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <h1 class="text-center">Destinations in <%= continent %> </h1>
            <hr>
            
            <% posts.each do |post| %>
                <div class="post-preview">
                    <%= link_to post do %>
                        <h2 class="post-title">
                            <%= post.title %>
                        </h2>
                        <h3 class="post-subtitle">
                            <%= ISO3166::Country.find_country_by_alpha2(post.country).name %>
                        </h3>
                        <h3 class="post-subtitle">
                            <%= post.subregion %>
                        </h3>
                    <% end %>
                    <p class="post-meta">Posted on <%= post.created_at.strftime("%B %d, %Y") %></p>
                </div>
                <hr>
            <% end %>
        </div>
    </div>
</div>
<% else %>
    <br>
    <h1 class="text-center">Looks like something went wrong</h1>
<% end %>

app/views/posts/new.html.erb
<div class="container">
    <div class="text-center">
        <br><br><br>
        <h1>New Post</h1>
        <%= render 'form' %>
    </div>
</div>

app/views/posts/show.html.erb
<header class="intro-header" style="background-image: url(<%= @post.image_url %>)">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1><%= @post.title %></h1>
                    <hr class="small">
                    <% c = ISO3166::Country.find_country_by_alpha2(@post.country) %>
                    <span class="subheading"><%= c.name %></span>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="text-center">
    <% if admin_signed_in? %>
        <%= link_to 'Edit |', edit_post_path %>
        <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    <% end %>
    </div>
    <h4 class="text-center">From Wikipedia:</h4>
    <div id="article"></div>

    <script>
        $.ajax({
            url: "https://en.wikipedia.org/w/api.php",
            data: {
                format: "json",
                action: "parse",
                page: "<%= @post.title %>",
                prop:"text",
                section:0,
            },
        dataType: 'jsonp',
        headers: {
            'Api-User-Agent': 'MyCoolTool/1.1 (http://example.com/MyCoolTool/; MyCoolTool@example.com) BasedOnSuperLib/1.4'
        },
        success: function (data) {
            
            var markup = data.parse.text["*"];
    		var i = $('<div></div>').html(markup);
    		
    		// remove links as they will not work
    		i.find('a').each(function() { $(this).replaceWith($(this).html()); });
    		
    		// remove any references
    		i.find('sup').remove();
    		
    		// remove cite error
    		i.find('.mw-ext-cite-error').remove();
    		
    		$('#article').html($(i).find('p'));
    
    
            }
            });
</script>

</div>
<br><br><br>